language: java
after_success: etc/travis-deploy.sh
sudo: false

jdk:
  - openjdk8
  - openjdk11

cache:
  directories:
    - '$HOME/.m2/repository'

env:
  global:
    - secure: "bP0rnmjzRGbXfN1WfjQAPSENDH9ID3OXcnwKdutqPnIpAjiSD46f9uF2XTSgOismBUlMFCZgGxkDG0ZNqbrGx5/o9oICEv266sz1KWlpTPT+H8DShX9COhzxXNjEMOIyKBkN9ABfLSjfAdxlrOaaSQOPa50+deX9mys/uooPZCk="
    - secure: "hMn2cTOfglg2A+xE+Zrm1EGMi7sLFV5N0D15CDb80HL5g66twLafeFQ2IfP2A9HecPwmnM/h3BYhNO0Wsn2MOctPSA1t48gG0aoYZHZCYiRDmk5NAL1cmnv70jFxEUe+lIPYkTB9mKKkvC8mAJV62xjdaAEDSUuwG3WD19/fA2s="
